image: atlassian/default-image:latest

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD r.nitram.at
          - docker build -t r.nitram.at/unifi ./unifi
          - docker push r.nitram.at/unifi