image: atlassian/default-image:latest

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - docker login --username $   --password $DOCKER_PASSWORD
          - ./build_all.sh    