image: atlassian/default-image:latest

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD r.nitram.at
          - ./build_all.sh
