image: docker

pipelines:
  default:
    - step:
        name: build dockerfiles
        script:
          - ls $BITBUCKET_CLONE_DIR
          - $BITBUCKET_CLONE_DIR/build_changes.sh
        services:
          - docker

options:
  docker: true
